# Generated by Django 4.2.3 on 2024-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('CNG', 'CNG'), ('LPG', 'LPG')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(choices=[('Tata', 'Tata'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('Mercedes', 'Mercedes'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Nissan', 'Nissan'), ('Mitsubishi', 'Mitsubishi'), ('Subaru', 'Subaru'), ('Mazda', 'Mazda'), ('Mitsubishi', 'Mitsubishi')], max_length=255)),
                ('fueltype', models.ManyToManyField(to='app.fueltypemodel')),
            ],
        ),
    ]
