# Generated by Django 4.2.3 on 2024-04-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='fueltype',
            new_name='fuel_name',
        ),
    ]
